services:
  fungi:
    build: .
    restart: always
  fuseki:
    image: "stain/jena-fuseki"
    restart: always
    ports:
      - 3030:3030
    environment:
      - FUSEKI_DATASET_1=my-knowledge-base
