services:
  fungi:
    build: .
    restart: always
    environment:
      - PORT=5000
      - FRONTEND_PORT=3000
      - FUNGUS_ID=1
    ports:
      - 5000:5000
    depends_on: [ fuseki ]
  fungi2:
    build: .
    restart: always
    environment:
      - PORT=5001
      - FRONTEND_PORT=3001
      - FUNGUS_ID=2
    ports:
      - 5001:5001
    depends_on: [ fuseki ]

  fungi-frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_PORT: 5000
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
    ports:
      - 3000:3000
    restart: always
    environment:
      - PORT=3000
    depends_on: [ fungi ]
  fungi-frontend2:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_PORT: 5001
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
    ports:
      - 3001:3001
    restart: always
    environment:
      - PORT=3001
    depends_on: [ fungi2 ]

  fuseki:
    image: "stain/jena-fuseki"
    restart: always
    ports:
      - 3030:3030
    environment:
      - FUSEKI_DATASET_1=my-knowledge-base
      - ADMIN_PASSWORD=pw123
