services:

# --------------------------------------------------------
# ------------ FUNGUS FUNCTIONALITY CONTAINER ------------
# --------------------------------------------------------
  fungus-backend:
    build: fungus-backend
    restart: always
    environment:
      - FUNGUS_BACKEND_PORT=5000
      - FUNGUS_FRONTEND_PORT=3000
      - FUNGUS_ID=1
      - PEER_AP_BACKEND_PORT=3004
      - PEER_AP_BACKEND_NAME=ap-backend2
      - AP_BACKEND_NAME=ap-backend
      - AP_BACKEND_PORT=3003
    ports:
      - 5000:5000
    depends_on: [ fuseki ]

  fungus-backend2:
    build: fungus-backend
    restart: always
    environment:
      - FUNGUS_BACKEND_PORT=5001
      - FUNGUS_FRONTEND_PORT=3001
      - FUNGUS_ID=2
      - PEER_AP_BACKEND_NAME=ap-backend
      - PEER_AP_BACKEND_PORT=3003
      - AP_BACKEND_NAME=ap-backend2
      - AP_BACKEND_PORT=3004
    ports:
      - 5001:5001
    depends_on: [ fuseki ]

# -------------------------------------------------
# ------------ ACTIVITY PUB CONTAINER -------------
# -------------------------------------------------
  ap-backend:
    build:
      context: ap-backend
    ports:
      - 3003:3003
    restart: always
    environment:
      - AP_BACKEND_PORT=3003
      - AP_BACKEND_NAME=ap-backend
      - FUNGUS_BACKEND_NAME=fungus-backend
      - FUNGUS_BACKEND_PORT=5000
    depends_on: [ fungus-backend ]

  ap-backend2:
    build:
      context: ap-backend
    ports:
      - 3004:3004
    restart: always
    environment:
      - AP_BACKEND_PORT=3004
      - AP_BACKEND_NAME=ap-backend2
      - FUNGUS_BACKEND_NAME=fungus-backend2
      - FUNGUS_BACKEND_PORT=5001
    depends_on: [ fungus-backend2 ]

# ---------------------------------------------------
# ------------ KNOWLEDGE BASE CONTAINER -------------
# ---------------------------------------------------
  fuseki:
    image: "stain/jena-fuseki"
    restart: always
    ports:
      - 3030:3030
    environment:
      - FUSEKI_DATASET_1=my-knowledge-base
      - ADMIN_PASSWORD=pw123

# ---------------------------------------------
# ------------ FRONTEND CONTAINER -------------
# ---------------------------------------------
  fungus-frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_FUNGUS_BACKEND_PORT: 5000
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
        REACT_APP_AP_BACKEND_PORT: 3003
    ports:
      - 3000:3000
    restart: always
    environment:
      - PORT=3000
    depends_on: [ fungus-backend ]

  fungus-frontend2:
    build:
      context: ./frontend
      args:
        REACT_APP_FUNGUS_BACKEND_PORT: 5001
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
        REACT_APP_AP_BACKEND_PORT: 3004
    ports:
      - 3001:3001
    restart: always
    environment:
      - PORT=3001
    depends_on: [ fungus-backend2 ]
