services:
  fungi:
    build: .
    restart: always
    depends_on: [ fuseki ]
  fungi-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
  fuseki:
    image: "stain/jena-fuseki"
    restart: always
    ports:
      - 3030:3030
    environment:
      - FUSEKI_DATASET_1=my-knowledge-base
      - ADMIN_PASSWORD=pw123
