services:

# --------------------------------------------------------
# ------------ FUNGI FUNCTIONALITY CONTAINER -------------
# --------------------------------------------------------
  fungi:
    build: .
    restart: always
    environment:
      - PORT=5000
      - FRONTEND_PORT=3000
      - FUNGUS_ID=1
      - PEER_SERVER_PORT=3003
      - PEER_SERVER_NAME=fungi-backend
    ports:
      - 5000:5000
    depends_on: [ fuseki ]

  fungi2:
    build: .
    restart: always
    environment:
      - PORT=5001
      - FRONTEND_PORT=3001
      - FUNGUS_ID=2
      - PEER_SERVER_PORT=3004
      - PEER_SERVER_NAME=fungi-backend2
    ports:
      - 5001:5001
    depends_on: [ fuseki ]

# -------------------------------------------------
# ------------ ACTIVITY PUB CONTAINER -------------
# -------------------------------------------------
  fungi-backend:
    build:
      context: ./backend
      args:
        REACT_APP_BACKEND_PORT: 5000
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
    ports:
      - 3003:3003
      - 8000:8000
    restart: always
    environment:
      - PORT=3003
      - FEDIFY_SERVER_NAME=fungi-backend
      - FUNGI_SERVER_NAME=fungi
      - FUNGI_SERVER_PORT=5000
    depends_on: [ fungi ]

  fungi-backend2:
    build:
      context: ./backend
      args:
        REACT_APP_BACKEND_PORT: 5001
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
    ports:
      - 3004:3004
    restart: always
    environment:
      - PORT=3004
      - FEDIFY_SERVER_NAME=fungi-backend2
      - FUNGI_SERVER_NAME=fungi2
      - FUNGI_SERVER_PORT=5001
    depends_on: [ fungi2 ]

# ---------------------------------------------------
# ------------ KNOWLEDGE BASE CONTAINER -------------
# ---------------------------------------------------
  fuseki:
    image: "stain/jena-fuseki"
    restart: always
    ports:
      - 3030:3030
    environment:
      - FUSEKI_DATASET_1=my-knowledge-base
      - ADMIN_PASSWORD=pw123

# ---------------------------------------------
# ------------ FRONTEND CONTAINER -------------
# ---------------------------------------------
  fungi-frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_PORT: 5000
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
    ports:
      - 3000:3000
    restart: always
    environment:
      - PORT=3000
    depends_on: [ fungi ]

  fungi-frontend2:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_PORT: 5001
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
    ports:
      - 3001:3001
    restart: always
    environment:
      - PORT=3001
    depends_on: [ fungi2 ]
