services:

# --------------------------------------------------------
# ------------ FUNGUS FUNCTIONALITY CONTAINER ------------
# --------------------------------------------------------
  fungus-backend0:
    build: fungus-backend
    restart: always
    environment:
      - FUNGUS_ID=0
    env_file: ".env"
    ports:
      - 5000:5000
    depends_on: [ fuseki ]

  fungus-backend1:
    build: fungus-backend
    restart: always
    environment:
      - FUNGUS_ID=1
    env_file: ".env"
    ports:
      - 5001:5001
    depends_on: [ fuseki ]

  fungus-backend2:
    build: fungus-backend
    restart: always
    environment:
      - FUNGUS_ID=2
    env_file: ".env"
    ports:
      - 5002:5002
    depends_on: [ fuseki ]

# -------------------------------------------------
# ------------ ACTIVITY PUB CONTAINER -------------
# -------------------------------------------------
  ap-backend0:
    build:
      context: ap-backend
    ports:
      - 3003:3003
    restart: always
    environment:
      - FUNGUS_ID=0
    env_file: ".env"
    depends_on: [ fungus-backend0 ]

  ap-backend1:
    build:
      context: ap-backend
    ports:
      - 3004:3004
    restart: always
    environment:
      - FUNGUS_ID=1
    env_file: ".env"
    depends_on: [ fungus-backend1 ]

  ap-backend2:
    build:
      context: ap-backend
    ports:
      - 3005:3005
    restart: always
    environment:
      - FUNGUS_ID=2
    env_file: ".env"
    depends_on: [ fungus-backend2 ]

# ---------------------------------------------------
# ------------ KNOWLEDGE BASE CONTAINER -------------
# ---------------------------------------------------
  fuseki:
    image: "stain/jena-fuseki"
    restart: always
    ports:
      - 3030:3030
    environment:
      - FUSEKI_DATASET_1=my-knowledge-base
      - ADMIN_PASSWORD=pw123

# ---------------------------------------------
# ------------ FRONTEND CONTAINER -------------
# ---------------------------------------------
  fungus-frontend0:
    build:
      context: ./frontend
      args:
        REACT_APP_FUNGUS_ID: 0
        REACT_APP_FUNGUS_BACKEND_PORT: ${FUNGUS_BACKEND_PORT}
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
        REACT_APP_AP_BACKEND_PORT: ${AP_BACKEND_PORT}
    ports:
      - 3000:3000
    restart: always
    env_file: ".env"
    environment:
      - PORT=3000
      - FUNGUS_ID=0
    depends_on: [ fungus-backend0 ]

  fungus-frontend1:
    build:
      context: ./frontend
      args:
        REACT_APP_FUNGUS_ID: 1
        REACT_APP_FUNGUS_BACKEND_PORT: ${FUNGUS_BACKEND_PORT}
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
        REACT_APP_AP_BACKEND_PORT: ${AP_BACKEND_PORT}
    ports:
      - 3001:3001
    restart: always
    env_file: ".env"
    environment:
      - PORT=3001
      - FUNGUS_ID=1
    depends_on: [ fungus-backend1 ]

  fungus-frontend2:
    build:
      context: ./frontend
      args:
        REACT_APP_FUNGUS_ID: 2
        REACT_APP_FUNGUS_BACKEND_PORT: ${FUNGUS_BACKEND_PORT}
        REACT_APP_SEMANTIC_URL: "http://localhost:3030"
        REACT_APP_SOCIAL_URL: "https://techhub.social/@myceliumweb"
        REACT_APP_AP_BACKEND_PORT: ${AP_BACKEND_PORT}
    ports:
      - 3002:3002
    restart: always
    env_file: ".env"
    environment:
      - PORT=3002
      - FUNGUS_ID=2
    depends_on: [ fungus-backend2 ]
