services:
  fungus:
    build: .
    restart: always
    environment:
      - PORT=5000
      - FRONTEND_PORT=3000
    ports:
      - 5000:5000
    depends_on: [ fuseki ]

  fungus-frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_PORT: 5000
    ports:
      - 3000:3000
    restart: always
    environment:
      - PORT=3000

  fuseki:
    image: "stain/jena-fuseki"
    restart: always
    ports:
      - 3030:3030
    environment:
      - FUSEKI_DATASET_1=my-knowledge-base
      - ADMIN_PASSWORD=pw123
